--------------------------------------------------------------------------------
-- KumanoMae 마이그레이션 — 커뮤니티 완전삭제 시 ORA-02292 방지
-- COMMUNITY_FILE / COMMUNITY_COMMENT / COMMUNITY_LIKE FK를 ON DELETE CASCADE로 전환
-- 이미 배포된 DB에 실행 (최신 DDL 원본에는 이미 CASCADE로 반영되어 있음 - 신규 설치는 불필요)
--------------------------------------------------------------------------------

-- 실제 제약조건명이 다르면 아래로 확인 후 맞춰서 실행
-- SELECT TABLE_NAME, CONSTRAINT_NAME
--   FROM USER_CONSTRAINTS
--  WHERE TABLE_NAME IN ('COMMUNITY_FILE','COMMUNITY_COMMENT','COMMUNITY_LIKE')
--    AND CONSTRAINT_TYPE = 'R';

ALTER TABLE COMMUNITY_FILE DROP CONSTRAINT FK_CFILE_CBOARD;
ALTER TABLE COMMUNITY_FILE ADD CONSTRAINT FK_CFILE_CBOARD
    FOREIGN KEY (C_BOARD_ID) REFERENCES COMMUNITY_BOARD (C_BOARD_ID) ON DELETE CASCADE;

ALTER TABLE COMMUNITY_COMMENT DROP CONSTRAINT FK_CCOMMENT_CBOARD;
ALTER TABLE COMMUNITY_COMMENT ADD CONSTRAINT FK_CCOMMENT_CBOARD
    FOREIGN KEY (C_BOARD_ID) REFERENCES COMMUNITY_BOARD (C_BOARD_ID) ON DELETE CASCADE;

ALTER TABLE COMMUNITY_LIKE DROP CONSTRAINT FK_CLIKE_CBOARD;
ALTER TABLE COMMUNITY_LIKE ADD CONSTRAINT FK_CLIKE_CBOARD
    FOREIGN KEY (C_BOARD_ID) REFERENCES COMMUNITY_BOARD (C_BOARD_ID) ON DELETE CASCADE;

COMMIT;

-- 확인
-- SELECT CONSTRAINT_NAME, DELETE_RULE FROM USER_CONSTRAINTS
--  WHERE TABLE_NAME IN ('COMMUNITY_FILE','COMMUNITY_COMMENT','COMMUNITY_LIKE') AND CONSTRAINT_TYPE = 'R';
-- DELETE_RULE 컬럼이 'CASCADE'로 나오면 정상 적용된 것