--------------------------------------------------------------------------------
-- 곰 출몰 위기 경보 및 정보 공유 시스템
-- Oracle DDL Script (CREATE TABLE / SEQUENCE / INDEX / VIEW)
-- 기준 문서: ERD 설계서 v3.0
-- 대상 DB : Oracle 11g 이상
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 0. 기존 객체 정리 (재실행 시 사용 - 최초 생성 시에는 주석 처리 상태로 둘 것)
--------------------------------------------------------------------------------
-- DROP VIEW V_MAP_MARKER;
-- DROP TABLE ADMIN_LOG PURGE;
-- DROP TABLE COMMUNITY_LIKE PURGE;
-- DROP TABLE COMMUNITY_COMMENT PURGE;
-- DROP TABLE COMMUNITY_FILE PURGE;
-- DROP TABLE COMMUNITY_BOARD PURGE;
-- DROP TABLE SEASON_ALERT PURGE;
-- DROP TABLE FACILITY PURGE;
-- DROP TABLE NEWS_ALERT PURGE;
-- DROP TABLE COMMENT PURGE;
-- DROP TABLE BOARD_FILE PURGE;
-- DROP TABLE BOARD PURGE;
-- DROP TABLE MEMBER PURGE;
-- DROP SEQUENCE MEMBER_ID_SEQ;
-- DROP SEQUENCE BOARD_ID_SEQ;
-- DROP SEQUENCE FILE_ID_SEQ;
-- DROP SEQUENCE COMMENT_ID_SEQ;
-- DROP SEQUENCE NEWS_ID_SEQ;
-- DROP SEQUENCE C_BOARD_ID_SEQ;
-- DROP SEQUENCE C_FILE_ID_SEQ;
-- DROP SEQUENCE C_COMMENT_ID_SEQ;
-- DROP SEQUENCE C_LIKE_ID_SEQ;
-- DROP SEQUENCE FACILITY_ID_SEQ;
-- DROP SEQUENCE ALERT_ID_SEQ;
-- DROP SEQUENCE LOG_ID_SEQ;


--------------------------------------------------------------------------------
-- 1. SEQUENCE 생성
--------------------------------------------------------------------------------
CREATE SEQUENCE MEMBER_ID_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BOARD_ID_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE FILE_ID_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMMENT_ID_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NEWS_ID_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE C_BOARD_ID_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE C_FILE_ID_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE C_COMMENT_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE C_LIKE_ID_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE FACILITY_ID_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ALERT_ID_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE LOG_ID_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;


--------------------------------------------------------------------------------
-- 2. MEMBER (회원)
--------------------------------------------------------------------------------
CREATE TABLE MEMBER (
    MEMBER_ID    NUMBER              NOT NULL,
    USER_ID      VARCHAR2(100 CHAR)  NOT NULL,
    USER_PW      VARCHAR2(200 CHAR)  NOT NULL,
    USER_NAME    VARCHAR2(100 CHAR)  NOT NULL,
    EMAIL        VARCHAR2(128 CHAR)  NOT NULL,
    PHONE        VARCHAR2(100 CHAR),
    USER_GRADE   CHAR(1)             DEFAULT 'M' NOT NULL,
    STATUS       CHAR(1)             DEFAULT 'Y' NOT NULL,
    JOIN_DATE    DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MEMBER            PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UQ_MEMBER_USER_ID    UNIQUE (USER_ID),
    CONSTRAINT CK_MEMBER_GRADE      CHECK (USER_GRADE IN ('M','A')),
    CONSTRAINT CK_MEMBER_STATUS     CHECK (STATUS IN ('Y','N'))
);

COMMENT ON TABLE  MEMBER              IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_ID    IS '회원 번호(PK)';
COMMENT ON COLUMN MEMBER.USER_ID      IS '로그인 아이디';
COMMENT ON COLUMN MEMBER.USER_PW      IS '비밀번호(해시 저장)';
COMMENT ON COLUMN MEMBER.USER_NAME    IS '이름/닉네임';
COMMENT ON COLUMN MEMBER.EMAIL        IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE        IS '연락처';
COMMENT ON COLUMN MEMBER.USER_GRADE   IS 'M:일반회원, A:관리자';
COMMENT ON COLUMN MEMBER.STATUS       IS 'Y:정상, N:탈퇴';
COMMENT ON COLUMN MEMBER.JOIN_DATE    IS '가입일';


--------------------------------------------------------------------------------
-- 3. BOARD (제보)
--------------------------------------------------------------------------------
CREATE TABLE BOARD (
    BOARD_ID       NUMBER              NOT NULL,
    MEMBER_ID      NUMBER              NOT NULL,
    TITLE          VARCHAR2(255 CHAR)  NOT NULL,
    CONTENT        CLOB                NOT NULL,
    RISK_LEVEL     VARCHAR2(20 CHAR)   NOT NULL,
    LATITUDE       NUMBER(10,7)        NOT NULL,
    LONGITUDE      NUMBER(10,7)        NOT NULL,
    ADDRESS        VARCHAR2(255 CHAR),
    SIGHTING_DATE  DATE                NOT NULL,
    SITUATION_TAG  VARCHAR2(255 CHAR),
    VIEW_CNT       NUMBER              DEFAULT 0 NOT NULL,
    STATUS         CHAR(1)             DEFAULT 'W' NOT NULL,
    CLEAR_YN       CHAR(1)             DEFAULT 'N' NOT NULL,
    CLEAR_DATE     DATE,
    CLEAR_MEMO     VARCHAR2(512 CHAR),
    REG_DATE       DATE                DEFAULT SYSDATE NOT NULL,
    MOD_DATE       DATE,
    CONSTRAINT PK_BOARD           PRIMARY KEY (BOARD_ID),
    CONSTRAINT FK_BOARD_MEMBER    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT CK_BOARD_RISK      CHECK (RISK_LEVEL IN ('DANGER','WARNING','CAUTION')),
    CONSTRAINT CK_BOARD_STATUS    CHECK (STATUS IN ('W','Y','N')),
    CONSTRAINT CK_BOARD_CLEAR_YN  CHECK (CLEAR_YN IN ('Y','N'))
);

CREATE INDEX IDX_BOARD_RISK_STATUS ON BOARD (RISK_LEVEL, STATUS, CLEAR_YN);
CREATE INDEX IDX_BOARD_REGDATE     ON BOARD (REG_DATE);

COMMENT ON TABLE  BOARD                IS '제보(위험정보) 게시글';
COMMENT ON COLUMN BOARD.BOARD_ID       IS '제보 번호(PK)';
COMMENT ON COLUMN BOARD.MEMBER_ID      IS '작성자(FK→MEMBER)';
COMMENT ON COLUMN BOARD.TITLE          IS '제목';
COMMENT ON COLUMN BOARD.CONTENT        IS '상세 내용';
COMMENT ON COLUMN BOARD.RISK_LEVEL     IS '위험도: DANGER/WARNING/CAUTION';
COMMENT ON COLUMN BOARD.LATITUDE       IS '위도';
COMMENT ON COLUMN BOARD.LONGITUDE      IS '경도';
COMMENT ON COLUMN BOARD.ADDRESS        IS 'Geocoder 자동 변환 주소';
COMMENT ON COLUMN BOARD.SIGHTING_DATE  IS '목격 일시';
COMMENT ON COLUMN BOARD.SITUATION_TAG  IS '목격 당시 상황 태그(콤마 구분)';
COMMENT ON COLUMN BOARD.VIEW_CNT       IS '조회수';
COMMENT ON COLUMN BOARD.STATUS         IS 'W:승인대기, Y:승인, N:반려';
COMMENT ON COLUMN BOARD.CLEAR_YN       IS '위험 해제 여부(Y=안심마커 전환)';
COMMENT ON COLUMN BOARD.CLEAR_DATE     IS '위험 해제 처리일';
COMMENT ON COLUMN BOARD.CLEAR_MEMO     IS '위험 해제 사유';
COMMENT ON COLUMN BOARD.REG_DATE       IS '등록일';
COMMENT ON COLUMN BOARD.MOD_DATE       IS '수정일';


--------------------------------------------------------------------------------
-- 4. BOARD_FILE (제보 첨부파일)
--------------------------------------------------------------------------------
CREATE TABLE BOARD_FILE (
    FILE_ID      NUMBER              NOT NULL,
    BOARD_ID     NUMBER              NOT NULL,
    ORIGIN_NAME  VARCHAR2(512 CHAR)  NOT NULL,
    SAVE_NAME    VARCHAR2(512 CHAR)  NOT NULL,
    FILE_PATH    VARCHAR2(512 CHAR)  NOT NULL,
    FILE_SIZE    NUMBER              NOT NULL,
    CONSTRAINT PK_BOARD_FILE        PRIMARY KEY (FILE_ID),
    CONSTRAINT FK_BOARDFILE_BOARD   FOREIGN KEY (BOARD_ID) REFERENCES BOARD (BOARD_ID)
);

COMMENT ON TABLE  BOARD_FILE             IS '제보 첨부파일';
COMMENT ON COLUMN BOARD_FILE.FILE_ID     IS '파일 번호(PK)';
COMMENT ON COLUMN BOARD_FILE.BOARD_ID    IS '소속 제보(FK→BOARD)';
COMMENT ON COLUMN BOARD_FILE.ORIGIN_NAME IS '원본 파일명';
COMMENT ON COLUMN BOARD_FILE.SAVE_NAME   IS '서버 저장 파일명(UUID)';
COMMENT ON COLUMN BOARD_FILE.FILE_PATH   IS '저장 경로';
COMMENT ON COLUMN BOARD_FILE.FILE_SIZE   IS '파일 크기(byte)';


--------------------------------------------------------------------------------
-- 5. COMMENT (제보 댓글)
--------------------------------------------------------------------------------
CREATE TABLE COMMENT (
    COMMENT_ID  NUMBER              NOT NULL,
    BOARD_ID    NUMBER              NOT NULL,
    MEMBER_ID   NUMBER              NOT NULL,
    CONTENT     VARCHAR2(512 CHAR)  NOT NULL,
    REG_DATE    DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_COMMENT          PRIMARY KEY (COMMENT_ID),
    CONSTRAINT FK_COMMENT_BOARD    FOREIGN KEY (BOARD_ID) REFERENCES BOARD (BOARD_ID),
    CONSTRAINT FK_COMMENT_MEMBER   FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE  COMMENT             IS '제보 댓글';
COMMENT ON COLUMN COMMENT.COMMENT_ID  IS '댓글 번호(PK)';
COMMENT ON COLUMN COMMENT.BOARD_ID    IS '소속 제보(FK→BOARD)';
COMMENT ON COLUMN COMMENT.MEMBER_ID   IS '작성자(FK→MEMBER)';
COMMENT ON COLUMN COMMENT.CONTENT     IS '댓글 내용';
COMMENT ON COLUMN COMMENT.REG_DATE    IS '등록일';


--------------------------------------------------------------------------------
-- 6. NEWS_ALERT (공식 뉴스/지자체 공지 - 크롤링 수집)
--------------------------------------------------------------------------------
CREATE TABLE NEWS_ALERT (
    NEWS_ID         NUMBER              NOT NULL,
    TITLE           VARCHAR2(255 CHAR)  NOT NULL,
    SUMMARY         VARCHAR2(1000),
    SOURCE_NAME     VARCHAR2(100 CHAR)  NOT NULL,
    SOURCE_TYPE     VARCHAR2(20 CHAR)   NOT NULL,
    SOURCE_URL      VARCHAR2(2000)      NOT NULL,
    RISK_LEVEL      VARCHAR2(20 CHAR),
    LATITUDE        NUMBER(10,7),
    LONGITUDE       NUMBER(10,7),
    REGION_TEXT     VARCHAR2(255 CHAR),
    PUBLISHED_DATE  DATE                NOT NULL,
    COLLECTED_DATE  DATE                DEFAULT SYSDATE NOT NULL,
    DUP_HASH        VARCHAR2(64 CHAR)   NOT NULL,
    CONSTRAINT PK_NEWS_ALERT        PRIMARY KEY (NEWS_ID),
    CONSTRAINT UQ_NEWS_DUP_HASH     UNIQUE (DUP_HASH),
    CONSTRAINT CK_NEWS_SOURCE_TYPE  CHECK (SOURCE_TYPE IN ('NEWS','GOV')),
    CONSTRAINT CK_NEWS_RISK         CHECK (RISK_LEVEL IN ('DANGER','WARNING','CAUTION'))
);

CREATE INDEX IDX_NEWS_PUBDATE ON NEWS_ALERT (PUBLISHED_DATE);

COMMENT ON TABLE  NEWS_ALERT                IS '공식 뉴스/지자체 공지(크롤링 수집)';
COMMENT ON COLUMN NEWS_ALERT.NEWS_ID         IS '뉴스/공지 번호(PK)';
COMMENT ON COLUMN NEWS_ALERT.TITLE           IS '뉴스 제목';
COMMENT ON COLUMN NEWS_ALERT.SUMMARY         IS '요약(크롤링 본문 일부)';
COMMENT ON COLUMN NEWS_ALERT.SOURCE_NAME     IS '출처명(언론사/지자체명)';
COMMENT ON COLUMN NEWS_ALERT.SOURCE_TYPE     IS 'NEWS:언론사, GOV:지자체 공지';
COMMENT ON COLUMN NEWS_ALERT.SOURCE_URL      IS '원문 링크';
COMMENT ON COLUMN NEWS_ALERT.RISK_LEVEL      IS '키워드 분석 기반 자동 추정 등급';
COMMENT ON COLUMN NEWS_ALERT.LATITUDE        IS '지역명→좌표 변환 결과(위도)';
COMMENT ON COLUMN NEWS_ALERT.LONGITUDE       IS '지역명→좌표 변환 결과(경도)';
COMMENT ON COLUMN NEWS_ALERT.REGION_TEXT     IS '원문에서 추출한 지역명';
COMMENT ON COLUMN NEWS_ALERT.PUBLISHED_DATE  IS '기사/공지 게시일';
COMMENT ON COLUMN NEWS_ALERT.COLLECTED_DATE  IS '스케줄러 수집 시각';
COMMENT ON COLUMN NEWS_ALERT.DUP_HASH        IS '제목+URL 해시값(중복 수집 방지)';


--------------------------------------------------------------------------------
-- 7. COMMUNITY_BOARD (커뮤니티: 후기/장비추천)
--------------------------------------------------------------------------------
CREATE TABLE COMMUNITY_BOARD (
    C_BOARD_ID  NUMBER              NOT NULL,
    MEMBER_ID   NUMBER              NOT NULL,
    CATEGORY    VARCHAR2(20 CHAR)   NOT NULL,
    TITLE       VARCHAR2(255 CHAR)  NOT NULL,
    CONTENT     CLOB                NOT NULL,
    GEAR_NAME   VARCHAR2(255 CHAR),
    VIEW_CNT    NUMBER              DEFAULT 0 NOT NULL,
    LIKE_CNT    NUMBER              DEFAULT 0 NOT NULL,
    STATUS      CHAR(1)             DEFAULT 'Y' NOT NULL,
    REG_DATE    DATE                DEFAULT SYSDATE NOT NULL,
    MOD_DATE    DATE,
    CONSTRAINT PK_COMMUNITY_BOARD      PRIMARY KEY (C_BOARD_ID),
    CONSTRAINT FK_CBOARD_MEMBER        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT CK_CBOARD_CATEGORY      CHECK (CATEGORY IN ('REVIEW','GEAR','FREE')),
    CONSTRAINT CK_CBOARD_STATUS        CHECK (STATUS IN ('Y','N'))
);

COMMENT ON TABLE  COMMUNITY_BOARD            IS '커뮤니티(산행/캠핑 후기, 장비추천) 게시글';
COMMENT ON COLUMN COMMUNITY_BOARD.C_BOARD_ID IS '커뮤니티 글 번호(PK)';
COMMENT ON COLUMN COMMUNITY_BOARD.MEMBER_ID  IS '작성자(FK→MEMBER)';
COMMENT ON COLUMN COMMUNITY_BOARD.CATEGORY   IS 'REVIEW:탐방후기, GEAR:장비추천, FREE:자유';
COMMENT ON COLUMN COMMUNITY_BOARD.TITLE      IS '제목';
COMMENT ON COLUMN COMMUNITY_BOARD.CONTENT    IS '본문';
COMMENT ON COLUMN COMMUNITY_BOARD.GEAR_NAME  IS '장비추천 글의 제품명';
COMMENT ON COLUMN COMMUNITY_BOARD.VIEW_CNT   IS '조회수';
COMMENT ON COLUMN COMMUNITY_BOARD.LIKE_CNT   IS '추천수(캐시)';
COMMENT ON COLUMN COMMUNITY_BOARD.STATUS     IS 'Y:노출, N:삭제(soft delete)';
COMMENT ON COLUMN COMMUNITY_BOARD.REG_DATE   IS '등록일';
COMMENT ON COLUMN COMMUNITY_BOARD.MOD_DATE   IS '수정일';


--------------------------------------------------------------------------------
-- 8. COMMUNITY_FILE (커뮤니티 첨부파일)
--------------------------------------------------------------------------------
CREATE TABLE COMMUNITY_FILE (
    C_FILE_ID    NUMBER              NOT NULL,
    C_BOARD_ID   NUMBER              NOT NULL,
    ORIGIN_NAME  VARCHAR2(512 CHAR)  NOT NULL,
    SAVE_NAME    VARCHAR2(512 CHAR)  NOT NULL,
    FILE_PATH    VARCHAR2(512 CHAR)  NOT NULL,
    CONSTRAINT PK_COMMUNITY_FILE   PRIMARY KEY (C_FILE_ID),
    CONSTRAINT FK_CFILE_CBOARD     FOREIGN KEY (C_BOARD_ID) REFERENCES COMMUNITY_BOARD (C_BOARD_ID)
);

COMMENT ON TABLE  COMMUNITY_FILE             IS '커뮤니티 게시글 첨부파일';
COMMENT ON COLUMN COMMUNITY_FILE.C_FILE_ID   IS '파일 번호(PK)';
COMMENT ON COLUMN COMMUNITY_FILE.C_BOARD_ID  IS '소속 게시글(FK→COMMUNITY_BOARD)';
COMMENT ON COLUMN COMMUNITY_FILE.ORIGIN_NAME IS '원본 파일명';
COMMENT ON COLUMN COMMUNITY_FILE.SAVE_NAME   IS '서버 저장 파일명';
COMMENT ON COLUMN COMMUNITY_FILE.FILE_PATH   IS '저장 경로';


--------------------------------------------------------------------------------
-- 9. COMMUNITY_COMMENT (커뮤니티 댓글)
--------------------------------------------------------------------------------
CREATE TABLE COMMUNITY_COMMENT (
    C_COMMENT_ID  NUMBER              NOT NULL,
    C_BOARD_ID    NUMBER              NOT NULL,
    MEMBER_ID     NUMBER              NOT NULL,
    CONTENT       VARCHAR2(512 CHAR)  NOT NULL,
    REG_DATE      DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_COMMUNITY_COMMENT  PRIMARY KEY (C_COMMENT_ID),
    CONSTRAINT FK_CCOMMENT_CBOARD    FOREIGN KEY (C_BOARD_ID) REFERENCES COMMUNITY_BOARD (C_BOARD_ID),
    CONSTRAINT FK_CCOMMENT_MEMBER    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE  COMMUNITY_COMMENT              IS '커뮤니티 댓글';
COMMENT ON COLUMN COMMUNITY_COMMENT.C_COMMENT_ID IS '댓글 번호(PK)';
COMMENT ON COLUMN COMMUNITY_COMMENT.C_BOARD_ID   IS '소속 게시글(FK→COMMUNITY_BOARD)';
COMMENT ON COLUMN COMMUNITY_COMMENT.MEMBER_ID    IS '작성자(FK→MEMBER)';
COMMENT ON COLUMN COMMUNITY_COMMENT.CONTENT      IS '댓글 내용';
COMMENT ON COLUMN COMMUNITY_COMMENT.REG_DATE     IS '등록일';


--------------------------------------------------------------------------------
-- 10. COMMUNITY_LIKE (커뮤니티 추천/좋아요)
--------------------------------------------------------------------------------
CREATE TABLE COMMUNITY_LIKE (
    C_LIKE_ID   NUMBER  NOT NULL,
    C_BOARD_ID  NUMBER  NOT NULL,
    MEMBER_ID   NUMBER  NOT NULL,
    REG_DATE    DATE    DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_COMMUNITY_LIKE     PRIMARY KEY (C_LIKE_ID),
    CONSTRAINT FK_CLIKE_CBOARD       FOREIGN KEY (C_BOARD_ID) REFERENCES COMMUNITY_BOARD (C_BOARD_ID),
    CONSTRAINT FK_CLIKE_MEMBER       FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT UQ_CLIKE_BOARD_MEMBER UNIQUE (C_BOARD_ID, MEMBER_ID)
);

COMMENT ON TABLE  COMMUNITY_LIKE             IS '커뮤니티 게시글 추천(좋아요)';
COMMENT ON COLUMN COMMUNITY_LIKE.C_LIKE_ID   IS '추천 번호(PK)';
COMMENT ON COLUMN COMMUNITY_LIKE.C_BOARD_ID  IS '대상 게시글(FK→COMMUNITY_BOARD)';
COMMENT ON COLUMN COMMUNITY_LIKE.MEMBER_ID   IS '추천 회원(FK→MEMBER)';
COMMENT ON COLUMN COMMUNITY_LIKE.REG_DATE    IS '추천일';


--------------------------------------------------------------------------------
-- 11. FACILITY (대피소/관할관청 위치정보)
--------------------------------------------------------------------------------
CREATE TABLE FACILITY (
    FACILITY_ID      NUMBER              NOT NULL,
    FACILITY_TYPE    VARCHAR2(20 CHAR)   NOT NULL,
    FACILITY_NAME    VARCHAR2(255 CHAR)  NOT NULL,
    LATITUDE         NUMBER(10,7)        NOT NULL,
    LONGITUDE        NUMBER(10,7)        NOT NULL,
    ADDRESS          VARCHAR2(255 CHAR),
    PHONE            VARCHAR2(100 CHAR),
    OPERATING_HOURS  VARCHAR2(255 CHAR),
    REG_DATE         DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FACILITY         PRIMARY KEY (FACILITY_ID),
    CONSTRAINT CK_FACILITY_TYPE    CHECK (FACILITY_TYPE IN ('SHELTER','GOV_OFFICE','POLICE'))
);

CREATE INDEX IDX_FACILITY_LOCATION ON FACILITY (LATITUDE, LONGITUDE);

COMMENT ON TABLE  FACILITY                  IS '대피소/등산로 안내소/관할관청·경찰 위치정보';
COMMENT ON COLUMN FACILITY.FACILITY_ID      IS '시설 번호(PK)';
COMMENT ON COLUMN FACILITY.FACILITY_TYPE    IS 'SHELTER/GOV_OFFICE/POLICE';
COMMENT ON COLUMN FACILITY.FACILITY_NAME    IS '시설명';
COMMENT ON COLUMN FACILITY.LATITUDE         IS '위도';
COMMENT ON COLUMN FACILITY.LONGITUDE        IS '경도';
COMMENT ON COLUMN FACILITY.ADDRESS          IS '주소';
COMMENT ON COLUMN FACILITY.PHONE            IS '연락처';
COMMENT ON COLUMN FACILITY.OPERATING_HOURS  IS '운영시간(대피소 한정)';
COMMENT ON COLUMN FACILITY.REG_DATE         IS '등록일';


--------------------------------------------------------------------------------
-- 12. SEASON_ALERT (시즌 특보 배너)
--------------------------------------------------------------------------------
CREATE TABLE SEASON_ALERT (
    ALERT_ID     NUMBER              NOT NULL,
    ALERT_TITLE  VARCHAR2(255 CHAR)  NOT NULL,
    SEASON_TYPE  VARCHAR2(20 CHAR)   NOT NULL,
    START_DATE   DATE                NOT NULL,
    END_DATE     DATE                NOT NULL,
    IS_ACTIVE    CHAR(1)             DEFAULT 'Y' NOT NULL,
    REG_DATE     DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_SEASON_ALERT      PRIMARY KEY (ALERT_ID),
    CONSTRAINT CK_ALERT_SEASON_TYPE CHECK (SEASON_TYPE IN ('SPRING','AUTUMN')),
    CONSTRAINT CK_ALERT_IS_ACTIVE   CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CK_ALERT_DATE_RANGE  CHECK (END_DATE >= START_DATE)
);

COMMENT ON TABLE  SEASON_ALERT              IS '계절별 시즌 특보 배너';
COMMENT ON COLUMN SEASON_ALERT.ALERT_ID     IS '특보 번호(PK)';
COMMENT ON COLUMN SEASON_ALERT.ALERT_TITLE  IS '배너 문구';
COMMENT ON COLUMN SEASON_ALERT.SEASON_TYPE  IS 'SPRING:동면해제기, AUTUMN:동면준비기';
COMMENT ON COLUMN SEASON_ALERT.START_DATE   IS '배너 노출 시작일';
COMMENT ON COLUMN SEASON_ALERT.END_DATE     IS '배너 노출 종료일';
COMMENT ON COLUMN SEASON_ALERT.IS_ACTIVE    IS '관리자 강제 On/Off';
COMMENT ON COLUMN SEASON_ALERT.REG_DATE     IS '등록일';


--------------------------------------------------------------------------------
-- 13. ADMIN_LOG (관리자 처리 이력)
--------------------------------------------------------------------------------
CREATE TABLE ADMIN_LOG (
    LOG_ID       NUMBER              NOT NULL,
    ADMIN_ID     NUMBER              NOT NULL,
    TARGET_TYPE  VARCHAR2(20 CHAR)   NOT NULL,
    TARGET_ID    NUMBER              NOT NULL,
    ACTION_TYPE  VARCHAR2(20 CHAR)   NOT NULL,
    ACTION_MEMO  VARCHAR2(512 CHAR),
    ACTION_DATE  DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ADMIN_LOG          PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_ADMINLOG_MEMBER    FOREIGN KEY (ADMIN_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT CK_ADMINLOG_TARGET    CHECK (TARGET_TYPE IN ('BOARD','COMMUNITY')),
    CONSTRAINT CK_ADMINLOG_ACTION    CHECK (ACTION_TYPE IN ('APPROVE','REJECT','DELETE','CLEAR'))
);

COMMENT ON TABLE  ADMIN_LOG              IS '관리자 승인/반려/삭제/해제 처리 이력';
COMMENT ON COLUMN ADMIN_LOG.LOG_ID       IS '로그 번호(PK)';
COMMENT ON COLUMN ADMIN_LOG.ADMIN_ID     IS '처리 관리자(FK→MEMBER)';
COMMENT ON COLUMN ADMIN_LOG.TARGET_TYPE  IS '처리 대상 구분: BOARD/COMMUNITY';
COMMENT ON COLUMN ADMIN_LOG.TARGET_ID    IS '대상 글 번호(BOARD_ID 또는 C_BOARD_ID)';
COMMENT ON COLUMN ADMIN_LOG.ACTION_TYPE  IS 'APPROVE/REJECT/DELETE/CLEAR';
COMMENT ON COLUMN ADMIN_LOG.ACTION_MEMO  IS '처리 사유 메모';
COMMENT ON COLUMN ADMIN_LOG.ACTION_DATE  IS '처리 일시';


--------------------------------------------------------------------------------
-- 14. 지도 통합 조회용 VIEW (회원 제보 + 공식 뉴스/지자체 공지 통합)
--------------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_MAP_MARKER AS
SELECT
    'USER'                 AS SOURCE_TYPE,
    BOARD_ID               AS TARGET_ID,
    TITLE,
    CASE WHEN CLEAR_YN = 'Y' THEN 'CLEARED' ELSE RISK_LEVEL END AS DISPLAY_RISK,
    LATITUDE, LONGITUDE, ADDRESS,
    SIGHTING_DATE          AS EVENT_DATE,
    REG_DATE
FROM BOARD
WHERE STATUS = 'Y'
UNION ALL
SELECT
    CASE WHEN SOURCE_TYPE = 'GOV' THEN 'OFFICIAL_GOV' ELSE 'OFFICIAL_NEWS' END,
    NEWS_ID,
    TITLE,
    NVL(RISK_LEVEL, 'CAUTION'),
    LATITUDE, LONGITUDE, REGION_TEXT,
    PUBLISHED_DATE,
    COLLECTED_DATE
FROM NEWS_ALERT
WHERE LATITUDE IS NOT NULL AND LONGITUDE IS NOT NULL;


--------------------------------------------------------------------------------
-- 15. 생성 결과 확인용 조회 (선택 실행)
--------------------------------------------------------------------------------
-- SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;
-- SELECT SEQUENCE_NAME FROM USER_SEQUENCES ORDER BY SEQUENCE_NAME;
-- SELECT VIEW_NAME FROM USER_VIEWS;

COMMIT;
